### ISSUE TITLE
Подготовим структуру

### ISSUE THREAD

**Issue by molefrog** [molefrog/wisdom#1]
Первое задание — создать начальную структуру node.js проекта. Склонировать репозиторий, добавить файлы:
-  `README.md` посмотри на формат Markdown. Напиши несколько предложений с заголовком: опиши проект, зачем он нужен (подсказка: это репозиторий, в котором мы будем хранить все твои домашние задание). Если затрудняешься, посмотри, как его оформляют в больших open-source проектах.
- Создай файл `package.json` (его можно сгенерировать с помощью `npm init` в папке с проектом). Постарайся заполнить все поля и быть креативнее. Вот [это](http://browsenpm.org/package.json) может оказаться полезным.
- Создай пустой файл `index.js`. Это будет нашей точкой входа в приложение.
- Добавь в проект `.gitignore`. Возможно, нужно будет воспользоваться генератором.

Старайся следить за тем, чтобы твои коммиты были атомарными и чистыми, а commit message понятными. Неважно, на русском или английском, но обязательно придерживайся одного языка, если выбрал его.

**Comment by Shugar** [comment]
Даже если я уже видел формат Markdown мне ведь все равно нужно написать Readme?

**Comment by molefrog** [comment]
@Shugar Ну конечно! Ты же должен понимать, что мы вообще делаем. А лучший способ это сделать — написать об этом.

**Comment by Shugar** [comment]
Готово.

**Comment by molefrog** [comment]
> Путь к мудрости и пониманию

Мне нравится название! Как ты так придумал?

**Comment by molefrog** [comment]
Тут все готово 🎉
