### ISSUE TITLE
Задание 1. Бесполезные функции

### ISSUE THREAD

**Issue by molefrog** [molefrog/wisdom#2]
Предлагаю написать модуль `src/useless-funcs.js`. Модуль будет содержать определение функций из списка ниже. Лучше всего, если с модулем ты будешь работать как с библиотекой и все их использования будешь хранить в `index.js` модуле.

Кстати, попробуй в `index.js` сделать что-то вроде тестовых кейсов, но только без тех обвязок, которые мы раньше писали. Наша задача здесь — научиться писать хорошие тестовые кейсы.

Вот пример:

``` JavaScript
// Тестирую функцию filter
console.log( filter([1,2,3], isOdd ); // [ 1, 3]
console.log( filter([2, 3], isEven ); // [ 2 ]
console.log( filter([], isOdd );      // краевой случай [ ]
```

Итак, функции:
- [x] Функция `isPrime`, которая принимает число и возвращает `true`, только если число простое. Подсказка: посмотри на определение простых чисел.
- [x] Функция `repeat`, которая принимает строку и число `n` и возвращает строку, повторенную `n` раз. Пример: `repeat("wat", 3) === "watwatwat"`
- [x] Функция `count`, которая принимает массив и значение и возвращает то, сколько раз это значение повторилось в массиве. Пример: `count(["wat", 3, null, 'wat'], 'wat') === 2`
- [x] Функция `countWhere`, такая же как `count`, только вместо элемента принимает предикат. 
- [x] Функция `lastDigit`, которая принимает число и возвращает последнюю _цифру_ этого числа. Например, последняя цифра числа _1337_ это _7_.
- [x] Функция `digits`, которая принимает число и возвращает массив его цифр. Пример: `digits(1337) === [ 1, 3, 3, 7 ]`

Некоторые из функций нетривиальны, поэтому даже если ты не в силах написать реализацию, опиши сигнатуру функции в файле (какие параметры принимает) и тестовые кейсы в `index.js`.
Это очень важно!

**Comment by Shugar** [comment]
Добавил функцию repeat.

**Comment by molefrog** [comment]
@Shugar Ммм.. Пока не увидел. Может, ты не запушил?

**Comment by Shugar** [comment]
Ветка task-1.
